# Generated by Django 6.0.7 on 2026-07-19 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "codigo",
                    models.CharField(max_length=20, verbose_name="Código / Ticker"),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome do Ativo"),
                ),
                (
                    "tipo_ativo",
                    models.CharField(
                        choices=[
                            ("ACOES", "Ações (B3)"),
                            ("FII", "Fundos Imobiliários (FIIs)"),
                            ("RENDA_FIXA", "Renda Fixa (CDB, LCI, Tesouro)"),
                            ("ETFS", "ETFs"),
                            ("CRIPTO", "Criptomoedas"),
                            (
                                "INTERNACIONAL",
                                "Investimentos no Exterior (Stocks/REITs)",
                            ),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ativo",
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Setor / Segmento",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ativos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="OperacaoInvestimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra / Aporte"),
                            ("VENDA", "Venda / Resgate"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Operação",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, verbose_name="Quantidade"
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Preço Unitário (R$)",
                    ),
                ),
                (
                    "taxas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Taxas e Corretagem (R$)",
                    ),
                ),
                ("data_operacao", models.DateField(verbose_name="Data da Operação")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operacoes",
                        to="investments.ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operacoes_investimento",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operação de Investimento",
                "verbose_name_plural": "Operações de Investimentos",
                "ordering": ["-data_operacao", "-created_at"],
            },
        ),
    ]
