# Generated by Django 6.0.7 on 2026-07-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Anonimização LGPD"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_anonymized",
            field=models.BooleanField(default=False, verbose_name="Conta Anonimizada"),
        ),
    ]
