# Generated by Django 6.0.7 on 2026-07-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="limite_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Limite Mensal (Orçamento)",
            ),
        ),
    ]
