# Generated by Django 6.0.7 on 2026-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categoria_limite_mensal"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="pilar",
            field=models.CharField(
                choices=[
                    ("ESSENCIAL", "Essenciais (Necessidades)"),
                    ("ESTILO_DE_VIDA", "Estilo de Vida (Desejos)"),
                    ("INVESTIMENTO", "Investimentos (Futuro)"),
                ],
                default="ESSENCIAL",
                max_length=20,
                verbose_name="Pilar do Orçamento Consciente",
            ),
        ),
    ]
