# Generated by Django 6.0.7 on 2026-07-19 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categoria_limite_mensal"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="confirmado",
            field=models.BooleanField(default=False, verbose_name="Confirmado / Pago"),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="mes_referencia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Mês de Referência (Competência)"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes",
                to="categories.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="data",
            field=models.DateField(verbose_name="Data da Transação"),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREDITO_1X", "Crédito À Vista"),
                    ("DEBITO", "Débito"),
                    ("PIX_TRANSFERENCIA", "PIX / Transferência"),
                    ("DINHEIRO", "Dinheiro"),
                    ("BOLETO", "Boleto"),
                ],
                max_length=50,
                null=True,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.CreateModel(
            name="ConfigCartao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "limite_cartao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Limite Disponível do Cartão",
                    ),
                ),
                (
                    "dia_fechamento",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Dia do Fechamento da Fatura"
                    ),
                ),
                (
                    "dia_vencimento",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Dia do Vencimento da Fatura"
                    ),
                ),
                (
                    "meta_fatura_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Meta Mensal de Fatura",
                    ),
                ),
                (
                    "reducao_mensal_desejada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Redução Mensal Desejada",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_cartao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Cartão",
                "verbose_name_plural": "Configurações dos Cartões",
            },
        ),
        migrations.CreateModel(
            name="Parcelamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, verbose_name="Descrição do Parcelamento"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Total Global",
                    ),
                ),
                (
                    "num_parcelas",
                    models.PositiveIntegerField(
                        verbose_name="Número Total de Parcelas"
                    ),
                ),
                (
                    "data_primeira_parcela",
                    models.DateField(verbose_name="Data da 1ª Parcela"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parcelamentos",
                        to="categories.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelamentos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcelamento",
                "verbose_name_plural": "Parcelamentos",
                "ordering": ["-data_primeira_parcela", "-created_at"],
            },
        ),
    ]
