# Generated by Django 6.0.7 on 2026-07-19 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0002_movimentacao_confirmado_movimentacao_mes_referencia_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configcartao",
            options={
                "ordering": ["apelido", "-created_at"],
                "verbose_name": "Configuração do Cartão",
                "verbose_name_plural": "Configurações dos Cartões",
            },
        ),
        migrations.AddField(
            model_name="configcartao",
            name="apelido",
            field=models.CharField(
                default="Cartão Principal",
                max_length=50,
                verbose_name="Apelido do Cartão",
            ),
        ),
        migrations.AddField(
            model_name="configcartao",
            name="ultimos_digitos",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="Últimos 4 Dígitos"
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="cartao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes",
                to="finance.configcartao",
                verbose_name="Cartão de Crédito",
            ),
        ),
        migrations.AddField(
            model_name="parcelamento",
            name="cartao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parcelamentos",
                to="finance.configcartao",
                verbose_name="Cartão de Crédito",
            ),
        ),
        migrations.AlterField(
            model_name="configcartao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartoes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
