# Generated by Django 6.0.7 on 2026-07-19 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_configcartao_options_configcartao_apelido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcelamento",
            name="cartao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelamentos",
                to="finance.configcartao",
                verbose_name="Cartão de Crédito",
            ),
        ),
    ]
