# Generated by Django 6.0.7 on 2026-07-19 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_parcelamento_cartao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanejamentoMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "mes_referencia",
                    models.DateField(verbose_name="Mês de Referência (1º dia do mês)"),
                ),
                (
                    "receita_esperada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Receita Mensal Esperada",
                    ),
                ),
                (
                    "meta_investimento_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Meta de Investimento Mensal",
                    ),
                ),
                (
                    "alocacao_essenciais_pct",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Percentual Essenciais (%)"
                    ),
                ),
                (
                    "alocacao_estilo_vida_pct",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Percentual Estilo de Vida (%)"
                    ),
                ),
                (
                    "alocacao_investimentos_pct",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Percentual Investimentos (%)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planejamentos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planejamento Mensal",
                "verbose_name_plural": "Planejamentos Mensais",
                "ordering": ["-mes_referencia"],
                "unique_together": {("usuario", "mes_referencia")},
            },
        ),
    ]
