# Generated by Django 6.0.7 on 2026-07-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_planejamentomensal"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="data_fim_recorrencia",
            field=models.DateField(
                blank=True,
                help_text="Deixe em branco para recorrência por tempo indeterminado",
                null=True,
                verbose_name="Data Final da Recorrência",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="frequencia_recorrencia",
            field=models.CharField(
                blank=True,
                choices=[("MENSAL", "Mensal"), ("ANUAL", "Anual")],
                default="MENSAL",
                max_length=20,
                null=True,
                verbose_name="Frequência de Recorrência",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="is_recorrente",
            field=models.BooleanField(default=False, verbose_name="É Recorrente?"),
        ),
    ]
